version: 2

references:
  steps: &steps
    - checkout
    - run: gem install bundler

    - restore_cache:
        key: nandi-bundler-{{ checksum "nandi.gemspec" }}
    - run: bundle install --path vendor/bundle
    - save_cache:
        key: nandi-bundler-{{ checksum "nandi.gemspec" }}
        paths:
          - vendor/bundle
    - run: bundle install
    - run: bundle exec rspec spec
    - run: bundle exec rubocop

jobs:
  ruby27:
    docker:
      - image: 'ruby:2.7'
    steps: *steps
  ruby26:
    docker:
      - image: 'ruby:2.6'
    steps: *steps
  ruby25:
    docker:
      - image: 'ruby:2.5'
    steps: *steps
  ruby24:
    docker:
      - image: 'ruby:2.4'
    steps: *steps

workflows:
  version: 2
  tests:
    jobs:
      - ruby27
      - ruby26
      - ruby25
      - ruby24
